# https://www.serverless.com/framework/docs/providers/aws/guide/deploying/

service: my-service

# Some of the arguments under provider can also be given when deploying,
# e.g. sls deploy --stage prod --region eu-west-1
provider:
    name: aws
    stage: dev
    region: eu-west-1
    runtime: python3.8

functions:
    my-function:  # The full function name in the AWS console will be {service_name}-{stage}-{function_name} 
        handler: handler.hello  # Reference to a function in a Python (handler) file

